### ISSUE TITLE
Support for Python 3.9?

### ISSUE THREAD

**Issue by prince2110** [LLNL/PolyClipper#11]
I am not at all experienced with C++ hence I am unable to develop shared object that would work for Python 3.9. I am in urgent need of this package. **Could you please say me when will this package be developed for Python 3.9 (or atleast for Python 3.7)?**

**Comment by jmikeowen** [comment]
Yep, we need to update to Python 3.  That should be happening during the next year (no concrete plans as yet).

**Comment by prince2110** [comment]
*Maybe a very stupid question to ask:* What if I transform all python code
to Python 3.9 in 'Pybind11wraps' directory? Will it be possible to build a
shared object that would work for Python 3?

Note: I have no experience with C++

**Comment by jmikeowen** [comment]
Nope, that won't do it.  We need to update some of the tools we rely on to Python3.  That's underway, so PolyClipper will be converted.

**Comment by prince2110** [comment]
Finally, I have somehow managed to build a shared object for Python3.7 by first generating ".cc" file (generated by Pybind11generator using python2.7) and then compiling it using python3.7 to obtain python3 compatible ".so" object.

I mentioned it here so that it might be helpful to someone who is facing similar issue.
