### ISSUE TITLE
Multiple plane cuts

### ISSUE THREAD

**Issue by nataraj2** [LLNL/PolyClipper#5]
Hi,

Can PolyClipper use multiple planes to cut out a `V` from a cube and retain the truncated cube like the image below? If yes, can you provide a simple C++ example to do this? Thanks.

<img width="796" alt="Screen Shot 2021-05-06 at 2 58 22 AM" src="https://user-images.githubusercontent.com/34353555/117271121-1f725700-ae17-11eb-94aa-284c512b90e4.png">

**Comment by jmikeowen** [comment]
Nope, that's not how it works.  PolyClipper can clip an arbitrary polygon with any set of planes, but they're infinite planes.  In the case posted here you would wind up clipping entirely across the original square with the two planes, resulting in an upward pointed corner.  Another way to put it is if you start with a convex polygon, all clipping operations will still result in a convex polygon.

**Comment by nataraj2** [comment]
Thank you. That is useful to know.
