### ISSUE TITLE
Counterclockwise Polyhedron

### ISSUE THREAD

**Issue by michael-schw** [LLNL/PolyClipper#6]
Hi, 
is it possible to get an counterclockwise-ordered Polyhedron? If yes how? I only know the counterclockwise-ordered of each points of the polyhedron. In the 2D case one can go along each vertex and take the neighbours.second.

Imagine the following example there ID=1is not counterclockwise to ID=4 if you take the whole polyhedron in count. I have no clue how to manage it. How do I know if a Polyhedron is aready counterclockwise-ordered.

![Unbenannt](https://user-images.githubusercontent.com/58597352/118607976-7e41b400-b7b9-11eb-84e2-e29f5c16bddb.JPG)

**Comment by jmikeowen** [comment]
I think you're asking for the faces in counter-clockwise ordering?  That is what the function "extractFaces" does in PolyClipper: it computes the faces as loops over vertices in counter-clockwise order.

**Comment by michael-schw** [comment]
That could be a solution.
